### ISSUE TITLE
Add more information to (Perfect) Dynamics model

### ISSUE THREAD

**Issue by piojanu** [piojanu/humblerl#8]
**Model should share information about world**. We need for example:
* state space size (we assume discrete state-space)
* action space size (we assume discrete action-space)
* **what actions are allowed in what states**

and PerfectDynamics should also be able to:
* tell if state is terminal,
* provide state value (if non-terminal then always 0, but for terminal states 1, 0 or -1 depending on whose turn it is and who won).

When you'll provide this information through PerfectDynamics methods, you can unify `__call__(state, action)` between PerfectDynamics and Dynamics. It means that in both interfaces it should return next state and reward (without done flag). Then you can make PerfectDynamics inherit after Dynamics and only extend it with additional methods.

[Here](https://github.com/suragnair/alpha-zero-general/blob/065d95cc7e35dfa6baa210e558ee05d8c6757a2a/Game.py) is good example of right interface for perfect information game.

## Definition of Done:
PerfectDynamics (and Dynamics) give access to listed world features.

## Next actions:
* [ ] Propose how to expose this information.
* [ ] Declare methods in the (Perfect)Dynamics interface.
* [ ] "Unify" PerfectDynamics and Dynamics (one extends another).

**Comment by Matioz** [comment]
It needs more analysis. As it is for two-player, adversarial and turn-based games we have to decide where should the information about the current player be found? 
* Inside Modeler facade as board game specific feature?
As currently Dynamics is stateless (returns next state based on given state and given action) it should be stateful to keep that information but how to decide when to change player?

* Outside Modeler facade as argument for __call__method?
Doesn't it break our previous assumptions that Planner is independent of Modeler/Dynamics and that it will be easy-to-use (for example with MCTS [processing tree with keeping information about current player])?

**Comment by piojanu** [comment]
We need to meet. It starts to become one big mess. I think we need to rethink this architecture one more time.

**Comment by piojanu** [comment]
Yep, we start fresh, so this issue is out of date.
